// <auto-generated />
using System;
using CustomersApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomersApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251203081926_Added orders seed data")]
    partial class Addedordersseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomersApp.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Göteborg",
                            CompanyName = "Volvo"
                        },
                        new
                        {
                            Id = 2,
                            City = "Trollhättan",
                            CompanyName = "Saab"
                        },
                        new
                        {
                            Id = 3,
                            City = "Södertälje",
                            CompanyName = "Scania"
                        },
                        new
                        {
                            Id = 4,
                            City = "Stockholm",
                            CompanyName = "Ericsson"
                        },
                        new
                        {
                            Id = 5,
                            City = "Älmhult",
                            CompanyName = "IKEA"
                        },
                        new
                        {
                            Id = 6,
                            City = "Jönköping",
                            CompanyName = "Husqvarna"
                        },
                        new
                        {
                            Id = 7,
                            City = "Stockholm",
                            CompanyName = "Electrolux"
                        },
                        new
                        {
                            Id = 8,
                            City = "Göteborg",
                            CompanyName = "SKF"
                        });
                });

            modelBuilder.Entity("CustomersApp.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            PriceTotal = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            PriceTotal = 2500m
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            PriceTotal = 3500m
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            PriceTotal = 4500m
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            PriceTotal = 5500m
                        });
                });

            modelBuilder.Entity("CustomersApp.Order", b =>
                {
                    b.HasOne("CustomersApp.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomersApp.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
